version: '3'

services:
  db:
    image: postgres
    restart: always
  web:
    image: starofthemoon/portfolio:1.0
    command: /bin/bash -c "sleep 40; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./portfolio:/portfolio"
    ports:
      - "8000:8000"
    depends_on:
      - db