# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=450)),
                ('link', models.URLField()),
                ('img_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgheader', to='portfolio.Image')),
                ('img_others', models.ManyToManyField(blank=True, related_name='imgothers', to='portfolio.Image')),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
    ]
