# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tag_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='Catégorie'),
        ),
    ]
