# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190118_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_header',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_others',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='portfolio.Project'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('S', 'Slider'), ('H', 'Header')], default='S', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_fr',
            field=models.TextField(max_length=450, null=True),
        ),
    ]
